# Generated by Django 3.2.8 on 2021-10-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo_bmw', models.ImageField(upload_to='Изображения/Y%/m%/%d')),
                ('car_bmw', models.TextField(blank=True)),
                ('photo_mercedes', models.ImageField(upload_to='Изображения/Y%/m%/%d')),
                ('car_mercedes', models.TextField(blank=True)),
                ('photo_porsche', models.ImageField(upload_to='Изображения/Y%/m%/%d')),
                ('car_porsche', models.TextField(blank=True)),
                ('created_content', models.DateTimeField(auto_now_add=True)),
                ('updated_content', models.DateTimeField(auto_now=True)),
                ('mb_published', models.BooleanField(default=True)),
            ],
        ),
    ]
