# Generated by Django 3.2.8 on 2021-11-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo_cars', models.ImageField(upload_to='Изображения/Y%/m%/%d', verbose_name='Фото')),
                ('car_info', models.TextField(blank=True, verbose_name='Информация')),
                ('created_content', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_content', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('mb_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'марку автомобиля',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['created_content', 'title'],
            },
        ),
    ]
