# Generated by Django 3.2.8 on 2021-10-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='car_bmw',
            new_name='car_info',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='photo_bmw',
            new_name='photo_cars',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='car_mercedes',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='car_porsche',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='photo_mercedes',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='photo_porsche',
        ),
    ]
