# Generated by Django 3.2.8 on 2021-10-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211013_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='car_info',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='created_content',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='mb_published',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='photo_cars',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='updated_content',
        ),
    ]
