# Generated by Django 3.2.8 on 2021-10-13 12:59

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211013_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='created_content',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='mb_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='photo_cars',
            field=models.ImageField(default=datetime.date(2021, 10, 13), upload_to='Изображения/Y%/m%/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='updated_content',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
