# Generated by Django 3.2.8 on 2021-10-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20211013_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
