# Generated by Django 3.2.8 on 2021-10-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_bmw', models.CharField(max_length=100)),
                ('ser_mercedes', models.CharField(max_length=100)),
                ('ser_porsche', models.CharField(max_length=100)),
            ],
        ),
    ]
