# Generated by Django 3.2.8 on 2021-11-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20211112_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['created_content', 'title'], 'verbose_name': 'Автомобили', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_info',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='created_content',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='mb_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='photo_cars',
            field=models.ImageField(upload_to='Изображения/Y%/m%/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Загаловок'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='updated_content',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
    ]
